/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_log;

import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import login_log.secondwindow;
public class login extends javax.swing.JFrame {

   
    public login() 
    {
        initComponents();
       sqlConnection con=new sqlConnection();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpasswordfield = new javax.swing.JPasswordField();
        jcombobox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jbtnreset = new javax.swing.JButton();
        jbtncancel = new javax.swing.JButton();
        jbtnlogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("USERNAME");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD");

        jpasswordfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jpasswordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordfieldActionPerformed(evt);
            }
        });
        jpasswordfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpasswordfieldKeyPressed(evt);
            }
        });

        jcombobox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrator", "salesman", "data entry operator" }));
        jcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboboxActionPerformed(evt);
            }
        });
        jcombobox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcomboboxKeyPressed(evt);
            }
        });

        jbtnreset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbtnreset.setText("RESET");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        jbtnreset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnresetKeyPressed(evt);
            }
        });

        jbtncancel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbtncancel.setText("CANCEL");
        jbtncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncancelActionPerformed(evt);
            }
        });
        jbtncancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtncancelKeyPressed(evt);
            }
        });

        jbtnlogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbtnlogin.setText("LOGIN");
        jbtnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnloginActionPerformed(evt);
            }
        });
        jbtnlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnloginKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnlogin)
                .addGap(6, 6, 6)
                .addComponent(jbtncancel)
                .addGap(6, 6, 6)
                .addComponent(jbtnreset)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnlogin)
                    .addComponent(jbtncancel)
                    .addComponent(jbtnreset))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("LOGIN WINDOW");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel2)
                        .addGap(182, 182, 182)
                        .addComponent(jcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel3)
                        .addGap(182, 182, 182)
                        .addComponent(jpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(530, 530, 530)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(535, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtncancelActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        
        jpasswordfield.setText(null);
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jbtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnloginActionPerformed
               String password=jpasswordfield.getText();
             
        if( (jcombobox.getSelectedItem()=="administrator") && password.equals("admin") )
        {
            jpasswordfield.setText(null);
            
             secondwindow sc =new secondwindow();
             sc.setVisible(true);
             setVisible(false);
            

    }//GEN-LAST:event_jbtnloginActionPerformed
        else if(password.equals("saleman") && (jcombobox.getSelectedItem()=="salesman"))
        {
            jpasswordfield.setText(null);
            
             secondwindow sc =new secondwindow();
             sc.setVisible(true);
             setVisible(false);
             
             
             
        }
         else if(password.equals("1234") && (jcombobox.getSelectedItem()=="data entry operator"))
        {
            jpasswordfield.setText(null);
            
             secondwindow sc =new secondwindow();
             sc.setVisible(true);
             setVisible(false);
        }
                
         else
        {
            JOptionPane.showMessageDialog(null,"invalid username or password","invalid login",JOptionPane.ERROR_MESSAGE);
            jpasswordfield.setText(null);
            
            
        }
    }
    private void jcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboboxActionPerformed
      
    }//GEN-LAST:event_jcomboboxActionPerformed

    private void jbtnloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnloginKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT)
        {
            jbtncancel.requestFocus();
        }
        else if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
               String password=jpasswordfield.getText();
             
        if( (jcombobox.getSelectedItem()=="administrator") && password.equals("admin") )
        {
            jpasswordfield.setText(null);
            
             secondwindow sc =new secondwindow();
             sc.setVisible(true);
             
             setVisible(false);
            

    }                                         
        else if(password.equals("saleman") && (jcombobox.getSelectedItem()=="salesman"))
        {
            jpasswordfield.setText(null);
           
             secondwindow sc =new secondwindow();
             sc.setVisible(true);
             setVisible(false);
        }
         else if(password.equals("1234") && (jcombobox.getSelectedItem()=="data entry operator"))
        {
            jpasswordfield.setText(null);
           
             secondwindow sc =new secondwindow();
             sc.setVisible(true);
             setVisible(false);
        }
         
                
         else
        {
            JOptionPane.showMessageDialog(null,"invalid username or password","invalid login",JOptionPane.ERROR_MESSAGE);
            jpasswordfield.setText(null);
            
            
        }
        }
        
        
    }//GEN-LAST:event_jbtnloginKeyPressed

    private void jpasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordfieldActionPerformed

    private void jpasswordfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpasswordfieldKeyPressed
         
            if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
                  String password=jpasswordfield.getText();
                  
             
        if( (jcombobox.getSelectedItem()=="administrator") && password.equals("admin") )
        {
            jpasswordfield.setText(null);
            
             secondwindow sc =new secondwindow();
             sc.setVisible(true);
             sc.setenable();
             setVisible(false);
             
            
           

    }                                         
        else if(password.equals("saleman") && (jcombobox.getSelectedItem()=="salesman"))
        {
            jpasswordfield.setText(null);
           
             secondwindow sc =new secondwindow();
             sc.setvisible();
             sc.setvisible1();
             sc.setVisible(true);
             setVisible(false);
             
             
        }
         else if(password.equals("1234") && (jcombobox.getSelectedItem()=="data entry operator"))
        {
            jpasswordfield.setText(null);
            
             secondwindow sc =new secondwindow();
              sc.setvisible();
              sc.setvisible2();
             sc.setVisible(true);
             setVisible(false);
             
             
        }
                
         else
        {
            JOptionPane.showMessageDialog(null,"invalid username or password","invalid login",JOptionPane.ERROR_MESSAGE);
            jpasswordfield.setText(null);
            
            
        }
            }
                
        
    }//GEN-LAST:event_jpasswordfieldKeyPressed

    private void jbtncancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtncancelKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_LEFT)
        {
            jbtnlogin.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT)
        {
            jbtnreset.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
      {
          
        System.exit(0);
      }
    }//GEN-LAST:event_jbtncancelKeyPressed

    private void jbtnresetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnresetKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_LEFT)
       {
            jbtncancel.requestFocus();
       }
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
       {
            jpasswordfield.setText(null);
       }
    }//GEN-LAST:event_jbtnresetKeyPressed

    private void jcomboboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboboxKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jpasswordfield.requestFocus();
        }
    }//GEN-LAST:event_jcomboboxKeyPressed

    
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtncancel;
    private javax.swing.JButton jbtnlogin;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JComboBox<String> jcombobox;
    private javax.swing.JPasswordField jpasswordfield;
    // End of variables declaration//GEN-END:variables
private void systemExit()
{
   
    WindowEvent winCloseing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
}
      


}
